dist: xenial
sudo: false
language: python

cache: pip

python:
  - "3.6"
  - "3.7"

install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - coverage combine && codecov

notifications:
  email: false
