dist: xenial
sudo: false
language: python

cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"

matrix:
  fast_finish: true
  include:
    - { python: "3.6", env: TOXENV=isort }


install:
  - pip install tox tox-travis

script:
  - tox

after_success:
  - pip install codecov
  - coverage combine && codecov

notifications:
  email: false
